export const serviceMap = {
    1: "Dọn dẹp",
    2: "Tổng vệ sinh nhà cửa",
    3: "Dọn dẹp sau sự kiện/tết",
    4: "Giữ trẻ tại nhà nguyên ngày",
    5: "Chăm sóc người cao tuổi tại nhà",
    6: "Nấu ăn theo bữa",
    7: "Nấu ăn theo tuần/tháng",
    8: "Giặt ủi",
    9: "Ủi quần áo",
    10: "Giặt hấp cao cấp",
    11: "Chăm sóc cây cảnh",
    12: "Tưới cây, cắt tỉa",
    13: "Tắm & cắt tỉa lông thú cưng",
    14: "Sửa chữa điện nước",
    15: "Sơn sửa nội thất nhỏ",
    16: "Thợ sửa chữa",
    17: "Giúp việc theo yêu cầu (dịch vụ VIP)",
    18: "Hỗ trợ vận chuyển đồ đạc nhẹ"
};  